### ISSUE TITLE
Just adding this to not be forgotten: Strategia compatiblity

### ISSUE THREAD

**Issue by Gordon-Dry** [severedsolo/MonthlyBudgets#3]
As I already mentioned in the forum:
https://forum.kerbalspaceprogram.com/index.php?/topic/147010-15-monthly-budgets-47-16102018/&do=findComment&comment=3475284

And also tried to apply here:
https://github.com/jrossignol/Strategia/issues/76

So either Strategia or MonthlyBudgets has to do the job.

But a generic compatibility would be better, so MonthlyBudgets should do it.

As you said:

> Oh that's easily fixed. Worst case I can have MB intercept any fund gains at all (will make it configurable though in case it's a bit too aggressive) - I'll add it to the next update.

**Comment by severedsolo** [comment]
Thanks for this - I've not forgotten, but big Oh Scrap update in the works first

**Comment by severedsolo** [comment]
This is on hold - originally my plan was to override all fund changes... I completely forgot that a) that includes  funds being spent, and b) it's massively aggressive and causes the game to crash when you override it at the wrong time.

So, unless @jrossignol adds some kind of event support to Strategia, I don't think this is possible right now.

**Comment by jrossignol** [comment]
It's actually really easy to make events for other mods (something I added
back when I was on the team for 1.2).  I'll reread this thread, but I'd
there's anything specific you need for events let me know.

I'll look to get this in the next strategia release.

**Comment by severedsolo** [comment]
Thanks mate, 

What I really need is an event when a strategy pays out funds (or similar) - so I can override it and convert the funds using MB's formula.

**Comment by severedsolo** [comment]
Closed down as I won't be working on MB after this release
